### PR TITLE
Fix plantuml output

### LINKED ISSUE #30: plantuml parameters seem not to work
the -syntax parameter a well as the expected output for the plantuml call seem not to work. I end up with files of size 0

### PR DESCRIPTION
**Pull request by ewie**
Fixes #30:
* `-syntax` option only checks `stdin` which is not used by this extension.
* Determine output file from input file instead of creating a temporary file for the output.

### CODE REVIEW

File: includes/Diagrams.php [hunk 1]
```diff
@@ -80,7 +81,16 @@ public function renderLocally( string $commandName, string $input, array $params
...
 		$tmpOutFiles = [];
 		foreach ( $outputFormats as $outputType => $outputFormat ) {
-			$tmpOutFiles[$outputType] = $tmpFactory->newTempFSFile( 'diagrams_out_', $outputFormat );
+			if ( $commandName === 'plantuml' ) {
+				// Determine plantuml output file via input file because we can only
+				// specify the output directory and not a specific file.
+				$info = pathinfo( $tmpGraphSourceFile->getPath() );
+				$outputPath = $info['dirname'] . '/' . $info['filename'] . '.' . $outputFormat;
+				$tmpOutFiles[$outputType] = new FSFile( $outputPath );
+				$input = "@startuml\n$input\n@enduml";
```
Comment (samwilson) [inline includes/Diagrams.php:90]: This wrapping in start/end is already being done below, so this results in double-wrapping.

File: includes/Diagrams.php [hunk 2]
```diff
@@ -80,7 +81,16 @@ public function renderLocally( string $commandName, string $input, array $params
...
+			} else {
+				$tmpOutFiles[$outputType] = $tmpFactory->newTempFSFile( 'diagrams_out_', $outputFormat );
+			}
 			if ( $commandName === 'plantuml' ) {
```
Comment (samwilson) [inline includes/Diagrams.php:94]: This conditional can probably now be removed.

File: includes/Diagrams.php [hunk 3]
```diff
@@ -80,7 +81,16 @@ public function renderLocally( string $commandName, string $input, array $params
 		$mapData = null;
 		$tmpOutFiles = [];
 		foreach ( $outputFormats as $outputType => $outputFormat ) {
-			$tmpOutFiles[$outputType] = $tmpFactory->newTempFSFile( 'diagrams_out_', $outputFormat );
+			if ( $commandName === 'plantuml' ) {
+				// Determine plantuml output file via input file because we can only
+				// specify the output directory and not a specific file.
+				$info = pathinfo( $tmpGraphSourceFile->getPath() );
+				$outputPath = $info['dirname'] . '/' . $info['filename'] . '.' . $outputFormat;
+				$tmpOutFiles[$outputType] = new FSFile( $outputPath );
```
Comment (samwilson) [inline includes/Diagrams.php:89]: Should use `TempFSFile`.

**Review by samwilson — CHANGES_REQUESTED** [review]
Thanks for this! Looks great.

File: includes/Diagrams.php (hunk 1 above)
Comment (ewie) [reply includes/Diagrams.php:90]: Copy-paste error. Interestingly, PlantUML ignores the double-wrapping.

File: includes/Diagrams.php (hunk 2 above)
Comment (ewie) [reply includes/Diagrams.php]: Done

File: includes/Diagrams.php (hunk 3 above)
Comment (ewie) [reply includes/Diagrams.php]: Done

**Review by samwilson — APPROVED** [review]
